"""LLM prompt templates for AI Intake Assistant."""

from .clarification import (
    TRIGGER_DETECTION_SYSTEM,
    TRIGGER_DETECTION_USER,
    QUESTION_GENERATION_SYSTEM,
    QUESTION_GENERATION_USER,
    INTELLIGENCE_GATHERING_SYSTEM,
)

__all__ = [
    "TRIGGER_DETECTION_SYSTEM",
    "TRIGGER_DETECTION_USER",
    "QUESTION_GENERATION_SYSTEM",
    "QUESTION_GENERATION_USER",
    "INTELLIGENCE_GATHERING_SYSTEM",
]
